######################################################################
# Automatically generated by qmake (3.0) Sun May 15 23:06:17 2016
######################################################################

TEMPLATE = app
TARGET = src
INCLUDEPATH += .

QT += widgets
LIBS += -lface -lopencv_core -lopencv_highgui
# Input
HEADERS += faceitem.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += faceitem.cpp main.cpp mainwindow.cpp
